swimming around in her americano 
watching her watching them
perched in her spot
her eyes dance to the rhythm of the steps of passersby
riddled with the conversations in the reflection behind her

she stirs me around, and I say goodbye to the corners of my cube
thank you for acknowledging that I’m still here

she opens her book and reads the same chapter for the first of five times
her eyes become glossy and her lip tautens 
she’s thinking of him
the words enter her head but they hop on the treadmill 
running over and over until he leaves 

don’t forget about me

she sits in the same spot every time
executes the same routine
reads the same words

my morning routine
watching the patriarchy assume the position
inhaling the liquid-brewed cocaine of techno-capitalism
exhaling the normalcy of human being
exchanging their bitter personalities for my sweet transaction with espresso.
